name: Java CI - Main branch

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        java: ['11']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1 # https://github.com/actions/setup-java
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-qalipsis-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-qalipsis-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-qalipsis-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-qalipsis-gradle-wrapper-

      - name: Build
        run: ./gradlew build

      - name: Prepare signing configuration
        env:
          SIGNING_KEY_ID: ${{ secrets.SONATYPE_OSS_SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SONATYPE_OSS_SIGNING_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.SONATYPE_OSS_SIGNING_PRIVATE_KEY_BASE_64 }}
        run:
          echo "signing.keyId=$SIGNING_KEY_ID" >> $HOME/.gradle/gradle.properties ;
          echo "signing.password=$SIGNING_PASSWORD" >> $HOME/.gradle/gradle.properties ;
          $SIGNING_PRIVATE_KEY | base64 --decode > /tmp/privateKey.txt ;
          echo "signing.secretKeyRingFile=/tmp/privateKey.txt" >> $HOME/.gradle/gradle.properties

      - name: Prepare publishing configuration
        env:
          OSSRH_USERNAME: ${{secrets.SONATYPE_OSS_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.SONATYPE_OSS_PASSWORD}}
        run:
          echo "ossrhUsername=$OSSRH_USERNAME" >> $HOME/.gradle/gradle.properties ;
          echo "ossrhPassword=$OSSRH_PASSWORD" >> $HOME/.gradle/gradle.properties ;

      - name: Publish artifacts
        run: ./gradlew publish --no-daemon
