name: Java CI - Main branch

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        java: [ '11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare publishing configuration
        env:
          JRELEASER_CONFIGURATION: ${{secrets.JRELEASER_CONFIGURATION}}
        run: |
          mkdir -p $HOME/.jreleaser
          echo "$JRELEASER_CONFIGURATION" > $HOME/.jreleaser/config.yml ;

      - name: Publish artifacts
        run: ./gradlew clean publish jreleaserFullRelease
